name: Deploy Backend Services

on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build backend
        run: mvn -B clean package -f backend/pom.xml

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}/backend:${{ github.sha }} ./backend

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}/backend:${{ github.sha }}

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment/backend/
