name: CI Checks

on:
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Backend Tests
        run: mvn test -f backend/pom.xml

      - name: Run Frontend Tests
        run: npm test --prefix frontend
